name:                tasker-service
version:             0.1.0.0
github:              "mikatammi/tasker"
license:             Apache-2.0
author:              "Mika Tammi"
maintainer:          "mikatammi@gmail.com"
copyright:           "2019 Mika Tammi"

extra-source-files: []

# Metadata used when publishing your package
synopsis:            Tasker - task management utility (HTTP backend service)
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mikatammi/tasker#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - tasker-service-api
  - servant-server
  - servant-auth-server
  - warp
  - aeson

executables:
  tasker-service-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasker-service

tests:
  tasker-service-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasker-service
